[package]
name = "assuan-server"
description = "Typed asynchronous Assuan server sessions, handlers and inquiries"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[dependencies]
assuan-protocol = { version = "0.1.0", path = "../assuan-protocol" }
assuan-transport = { version = "0.1.0", path = "../assuan-transport" }
tokio = { workspace = true, features = ["time", "rt", "sync", "macros"] }
zeroize.workspace = true
thiserror.workspace = true
log.workspace = true

[dev-dependencies]
assuan-client = { path = "../assuan-client" }
tokio = { workspace = true, features = ["macros", "rt", "io-util", "test-util"] }

[lints]
workspace = true
